default_language_version:
  python: python3.12

default_stages: [commit, push]

repos:
  - repo: local
    hooks:
      # Prevent committing .rej files
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-toml
        exclude: .github/
      - id: check-yaml
        args: [--unsafe]
        exclude: |
          ^\.github/.*$
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        types: [python, pyi, jupyter]

      - id: ruff-format
        types: [python, pyi, jupyter]
        language: system

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-fix
        args: [--disable=MD013]
