# .github/workflows/publish-release.yml
name: Publish release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check-permission:
    name: check permission
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: shogo82148/actions-check-permissions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    needs:
      - check-permission
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git for GitHub Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract version from branch name
        id: extract_version
        run: |
          # Extract version from the branch name (e.g., release/v1.2.3 -> 1.2.3)
          version="${GITHUB_REF#refs/heads/release/v}"
          echo "Extracted version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff-changelog
        with:
          version: latest
          config: cliff.toml
          args: --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit CHANGELOG.md update
        run: |
          set +e
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG for version ${{ steps.extract_version.outputs.version }}"
          git branch -m main
          git push origin HEAD --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          tag_name: "v${{ steps.extract_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
